# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2           # Correctly indented under 'steps'
      inputs:                  # Correctly indented under 'task'
        containerRegistry: 'docker'
        repository: 'nizarmlaouihi/my-repo'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'  # Direct path since it's in the root
        tags: |
          $(tag)
